bukutamu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from . import views
app_name = 'bukutamu'

urlpatterns = [
	path('', views.index, name='index'),
	path('form', views.form, name='form'),
    path ('laporan', views.laporan, name = 'laporan'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
]

e_bukutamu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('tamu/', include('bukutamu.urls')),
    path('admin/', admin.site.urls),
    path('pelaporan/', include('pelaporan.urls')),
    path('', views.home),
    path('accounts/', include('django.contrib.auth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bukutamu/models.py
import datetime
import os
from django.db import models
from django.utils import timezone


class Tamu(models.Model):
    uid = models.CharField(max_length = 12)
    tipeid = models.CharField(max_length = 20)
    nama_tamu = models.CharField(max_length = 100,null = True)
    no_hp_tamu = models.CharField(max_length = 30,null = True)
    jenis_kelamin = models.CharField(max_length = 20,null = True)
    signed_in = models.BooleanField(null = True)
    perusahaan = models.CharField(max_length = 100,null = True)
    terakhir_datang = models.DateTimeField('terakhir_datang',null = True)
    image = models.ImageField(upload_to= "camera/",null = True)
    uid.default = '000000000000'
    saved = models.BooleanField()
    saved.default = True
    def delete_image(self):
        path = os.path.join(os.path.join(os.getcwd(), "media"), self.image.name)
        try:
            os.remove(path)
        except:
            pass
    def checkme(self):
        returned = [self.nama_tamu, self.terakhir_datang]
        return returned
    def last(self):
        #bool terakhir datang 30 hari terakhir
        return self.terakhir_datang >= timezone.now() - datetime.timedelta(days=30)
    def dest(self):

        return True

    def __str__(self):
        if(self.nama_tamu != None):
            return self.nama_tamu
        else:
            return "-"

class Departemen(models.Model):
    nama_departemen = models.CharField(max_length = (50))
    penanggungjawab = models.CharField(max_length = (50))
    email = models.CharField(max_length = (50))
    def __str__(self):
        return self.nama_departemen

class Year (models.Model):
    year = models.IntegerField()

class Kedatangan(models.Model):
    tamu = models.ForeignKey(Tamu, on_delete= models.CASCADE)
    tanggal_kedatangan = models.DateTimeField("datang")
    bertemu_dengan = models.CharField(max_length=(100))
    departemen = models.ForeignKey(Departemen,models.SET_NULL,blank=True,null=True,)
    alasan_kedatangan = models.CharField(max_length = 300)
    tanggal_keluar = models.DateTimeField("keluar")
    lama_kedatangan = models.DurationField("lama")
    suhu_badan = models.DecimalField(max_digits=5, decimal_places=2)
    terdapat_luka_terbuka = models.BooleanField()
    sakit =models.CharField(max_length=(100), null = True)
    out = models.BooleanField()
    def signout (self):
        self.tanggal_keluar = timezone.now()
        self.lama_kedatangan = self.tanggal_keluar - self.tanggal_kedatangan
        self.out = True

    def checkme(self):
        returned = [self.tamu, self.alasan_kedatangan, self.tanggal_kedatangan]
        return returned

bukutamu/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import get_object_or_404, render
from base64 import b64decode
from django.core.files.base import ContentFile
from django.http import Http404
from .models import Tamu, Kedatangan, Departemen, Year
from django.utils import timezone
from django.urls import reverse
import re
import os
from django.http import JsonResponse
# Create your views here.

def index(request):
    
    return render(request, 'bukutamu/index.html')

def b64toMime(b64_text):
    image_data = b64decode(b64_text)
    return image_data

def form (request):
    formdata = {}
    formdata ["uid"] = request.POST['UID']
    formdata['flag_auth'] ="true"
    try:
        # searching existing tamu's data
        tamu = Tamu.objects.get(uid = request.POST['UID'])
        if (tamu.jenis_kelamin == "Perempuan"):
            formdata["kelamin"] = True
        if (tamu.tipeid == "SIM"):
            formdata["tipid"] = True
        
        formdata["flag"] = True
        if (tamu.signed_in == True):
            formdata["flag"] = False
            kedatangan = tamu.kedatangan_set.get(out = False)
            a = kedatangan.departemen
            departemens = [a]
            formdata["kedatangan"]= kedatangan
            formdata['sakit'] = len(kedatangan.sakit) != 0
            formdata['save'] = tamu.saved
        else:
            departemens = Departemen.objects.all()
        formdata['departemen'] = departemens
        formdata['tamu'] = tamu
        # return JsonResponse()
        pelanggaran = tamu.pelaporan_set.count()
        formdata['flag_auth'] ="true"
        if (formdata['flag'] and pelanggaran >= 3):
            formdata['flag_auth'] ="false"
        kedatangan_dulu = tamu.kedatangan_set.all()
        kedatangan_dulu = kedatangan_dulu.order_by('-id')
        kedatangan_dulu = list(kedatangan_dulu)
        if len(kedatangan_dulu)>3:
            kedatangan_dulu= kedatangan_dulu[:3]
            a = kedatangan_dulu[2]
            kedatangan_dulu[2] = kedatangan_dulu[0]
            kedatangan_dulu[0]=a
        for item in kedatangan_dulu:
            item.tanggal_keluar = item.tanggal_keluar.date()

        formdata["history"] = kedatangan_dulu
        # tamu.image = tamu.image.url
        # tamu.image = tamu.image.split("/")
        # tamu.image = tamu.image[len(tamu.image)-1]

    except (KeyError, Tamu.DoesNotExist):
        departemens = Departemen.objects.all()
        formdata['departemen'] = departemens
        formdata["flag"] = True

    return render(request, "bukutamu/form.html", formdata)


def signin(request):
    
    image = request.POST['Image']
    image = b64decode(image)
    image = ContentFile(image, request.POST['UID'])

    try:
        tamu = Tamu.objects.get(uid = request.POST['UID'])
        tamu.signed_in = True
        tamu.delete_image()
        tamu.image = image
        tamu.saved = True if request.POST['save'] == "Ya" else False
        tamu.save()
        pelanggaran = tamu.pelaporan_set.filter(positif = False).count()
        
        if (pelanggaran >= 3):
            tamu.signed_in = False
            tamu.save()
            return HttpResponseRedirect(reverse('bukutamu:index'))

    except (KeyError, Tamu.DoesNotExist):
        #if not exist create new
        tamu = Tamu(
            uid = request.POST['UID'],
            tipeid = request.POST['TID'],
            nama_tamu = request.POST['Nama'],
            no_hp_tamu = request.POST['NoHP'],
            jenis_kelamin = request.POST['Kelamin'],
            perusahaan = request.POST['Institusi'],
            terakhir_datang = timezone.now(),
            image = None,
            signed_in = True,
            saved = True if request.POST['save'] == "Ya" else False
            )
        tamu.image = image
        tamu.save()
    a = timezone.now()
    years = Year.objects.all()
    year = []
    for item in years:
        year.append(years.year)
    if not (timezone.now().year in year):
        year = Year(year = timezone.now().year)
        year.save()
    tamu.kedatangan_set.create(
        tanggal_kedatangan = a,
        bertemu_dengan = request.POST['Bertemu'],
        alasan_kedatangan = request.POST['Keperluan'],
        tanggal_keluar = a,
        lama_kedatangan = a - a,
        suhu_badan = request.POST['Suhu'],
        terdapat_luka_terbuka = request.POST['Luka'],
        out = False,
        sakit = request.POST['Sakit'],
        departemen = Departemen.objects.get(id = request.POST['departemen'])
        )
    return HttpResponseRedirect(reverse('bukutamu:index'))

def signout(request):
    tamu = Tamu.objects.get(uid = request.POST['UID'])
    if not tamu.saved :
        tamu.tipeid = None
        tamu.nama_tamu = None
        tamu.no_hp_tamu = None
        tamu.jenis_kelamin = None
        tamu.terakhir_datang = None
        tamu.image = None
        tamu.saved = None
        tamu.signed_in = False
        tamu.save()
    tamu.signed_in = False
    tamu.save()        
    kedatangan = tamu.kedatangan_set.get(out = False)
    kedatangan.signout()
    kedatangan.save()
    return HttpResponseRedirect(reverse('bukutamu:index'))

def test(request):
    return render(request, 'bukutamu/test.html')

def laporan(request):
    return render(request, 'bukutamu/laporan.html')

bukutamu/templates/bukutamu/form.html
<head>
    {% load static %}
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" id="bootstrap-css">
    <script src="{% static "jquery.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "bukutamu/css/form.css" %}" rel="stylesheet">
    <!------ Include the above in your HEAD tag ---------->
    <title>Bukutamu</title>

</head>

<body background="{% static "indexbackground.jpg" %}" style="font-size: 15px" >
 <div class="wrapper" > 
  <div id="formContent">
   <div class="row vertical-align">
    <div class="col-sm-6" >
      {%if flag%}
          <video id="player" controls autoplay width="90%" ></video>
          <canvas id="canvas" class="col-sm-12" hidden=""></canvas>
      {%else%}
          {% with '/'|add:tamu.image.url as image_static %} 
              <img src = "{{tamu.image.url}}" width=100% height=56%></img>
          {% endwith %}
          
      {%endif%}
      <br>
      <br>
      <div class="row">
      	<div class="table-responsive col-sm-12">
		  <table class="table ">
		    <thead>
		      <tr >
		        <th class="w-25">Tanggal</th>
		        <th class="w-25">Bertemu dengan</th>
		        <th class="w-50">Keperluan</th>
		      </tr>
		    </thead>
		    <tbody>
		    {%for item in history%}
		      <tr >
		        <td>{{item.tanggal_keluar}}</td>
		        <td>{{item.bertemu_dengan}}</td>
		        <td>{{item.alasan_kedatangan }}</td>
		      </tr>
		    {%endfor%}
		    </tbody>
		  </table>
		</div>
      </div>
      
    </div>
    <div class="col-sm-6 v-divider">
        {%if flag%}
          <form method = "POST" action = {%url 'bukutamu:signin'%} class = "text-left"  onsubmit="validateForm()">
        {%else%}
            <form method = "POST" action = {%url 'bukutamu:signout'%} class = "text-left">
        {%endif%}
  			{% csrf_token %}
  			<input type="hidden" name="image_location" id="image_location" value="/images/bleh.jpg" 
  			 {%if not flag%} readonly {%endif%}><br>
	        <div class="form-group row"><!-- UID -->
	          <label class="control-label col-sm-3" for="UID">UID:</label>
	          <div class="col-sm-6">  
	            <input type="text" class="form-control inputsm" name="UID" id="UID" placeholder="UID" value = {{uid}} readonly > 
	          </div>
	          <div class="col-sm-3">
	            <select class="form-control inputsm" name="TID" id="TID" placeholder="Tipe id"  value = {{tamu.tipeid}} {%if not flag%} readonly {%endif%}>
	            	<option>KTP</option>
	            	<option {%if tipid%}selected{%endif%}>Kartu Pegawai</option>
	            	<option {%if tipid%}selected{%endif%}>SIM</option>
	            </select>
	          </div>
	        </div>

	        <div class="form-group row"> <!-- nama -->
	          <label class="control-label col-sm-3" for="Nama">Nama:</label>
	          <div class="col-sm-9">  
	            <input type="text" class="form-control inputsm" name="Nama" id="Nama"  placeholder="Nama" {%if not flag%} readonly {%endif%} required  {%if tamu.nama_tamu%} readonly value = {{tamu.nama_tamu}} {%endif%}  >
	          </div>
	        </div>
	        <div class="form-group row"> <!-- no HP -->
	          <label class="control-label col-sm-3" for="NoHP">Nomor HP:</label>
	          <div class="col-sm-9">  
	            <input type="number" class="form-control inputsm" name="NoHP" id="NoHP" placeholder="08xxxxxxxxxx" autocomplete="off" required {%if tamu.no_hp_tamu%} readonly value = {{tamu.no_hp_tamu}} {%endif%} {%if not flag%} readonly {%endif%}>
	          </div>
	        </div>
	        <div class="form-group row"><!-- Jenis kelamin -->
	          <label class="control-label col-sm-3" for="kelamin">Jenis Kelamin:</label>
	          <div class="col-sm-9">  
	            <select class="form-control inputsm" name="Kelamin" id="Kelamin" placeholder="L/P" {%if tamu.jenis_kelamin %} disabled value = {{tamu.jenis_kelamin}} {%endif%} {%if not flag%} readonly {%endif%}>
	            	<option>Laki laki</option>
				    <option {%if kelamin%}selected{%endif%}>Perempuan</option>
	            </select>
	          </div>
	        </div>
	        <div class="form-group row"> <!-- Institusi  -->
	          <label class="control-label col-sm-3" for="Institusi">Institusi:</label>
	          <div class="col-sm-9">  
	            <input type="text" class="form-control inputsm" name="Institusi" id="Institusi" placeholder="Institusi" required {% if tamu.perusahaan%} readonly value = {{tamu.perusahaan}} {%endif%} {%if not flag%} readonly {%endif%}>
	          </div>
	        </div>
	        <div class="form-group row"> <!-- SUhu badan -->
	          <label class="control-label col-sm-3" for="SuhuBadan">Suhu Badan:</label>
	          <div class="col-sm-9">  
	            <input type="number" step="any" class="form-control inputsm" name="Suhu" id="Suhu" placeholder="xx,x" required value = {{kedatangan.suhu_badan}} {%if not flag%} readonly {%endif%}>
	          </div>
	        </div>
	        <div class="form-group row"> <!-- BErtemu dengan -->
	          <label class="control-label col-sm-3" for="Bertemu">Bertemu dengan:</label>
	          <div class="col-sm-9">  
	            <input type="text" class="form-control inputsm" name="Bertemu" id="Bertemu"
	            placeholder="Bapak/Ibu" required value = {{kedatangan.bertemu_dengan}} {%if not flag%} readonly {%endif%}>
	          </div>
	        </div>
	        <div class="form-group row"> <!-- BErtemu dengan -->
	          <label class="control-label col-sm-3" for="Bertemu">Departemen:</label>
	          <div class="col-sm-9">  
	            <select type="text" class="form-control inputsm" name="departemen" id="departemen" required {%if not flag%} disabled {%endif%} 
	            >
	            	{%for item in departemen%}
	            	<option value={{item.id}} 
	            	{%if item.id == kedatangan.departemen%}
	            	selected
	            	{%endif%}
	            	>{{item.nama_departemen}}</option>
	            	{%endfor%}
	        	</select>
	          </div>
	        </div>
	        <div class="form-group row"> <!-- Keperluan -->
	          <label class="control-label col-sm-3" for="Keperluan">Keperluan:</label>
	          <div class="col-sm-9">  
	            <input type="text" class="form-control inputsm" name="Keperluan" id="Keperluan" placeholder="Untuk" required value = {{kedatangan.alasan_kedatangan}} {%if not flag%} readonly {%endif%}>
	          </div>
	        </div>
	        <div class="form-group row ">
	          <label class="control-label col-sm-5" for="Luka">Terdapat Luka terbuka:</label>
	      	<!-- </div>
	      	<div class="form-group row"> -->
	          	<label class="radio-inline col-sm-2">
	            <input type="radio"  name="Luka" id="Luka1" {% if kedatangan.terdapat_luka_terbuka%} checked=true  {%endif%}{%if not flag%}  disabled {%endif%} {%if not flag%}  disabled {%endif%} value = "1"> Ya
	        	</label>
	        	<label class="radio-inline col-sm-2">
	            <input type="radio"  name="Luka" id ="Luka2"{%if not flag%}  disabled {%endif%} {% if not  kedatangan.terdapat_luka_terbuka%} checked=true {%endif%} id = Luka value="0"> Tidak
	        	</label>
	        </div>
	        <div class="form-group row">
	          <label class="control-label col-sm-5" for="sakit"> Sakit dalam 3 hari terakhir:</label>
	          	<label class="radio-inline col-sm-2">
	            <input type="radio"  name="sakit" id="sakit_radio_y" {% if  sakit%} checked=true  {%endif%}{%if not flag%}  disabled {%endif%} onchange="sakit_aktive()"> Ya
	        	</label>
	        	<label class="radio-inline col-sm-2">
	            <input type="radio"  name="sakit" id="sakit_radio_n" value = "Tidak" {% if not sakit%} checked=true {%endif%}{%if not flag%} disabled {%endif%}  onchange="sakit_aktive()"> Tidak
	        	</label>

	        </div>
	        <div class="form-group row " >
	        <label class="control-label col-sm-3" for="sakit"> Jenis sakit :</label>
	          <div class="col-sm-9">  
	          	
	            <input type="text" class="form-control input-sm " name="Sakit" id="Sakit"  placeholder="Sehat" {%if not flag%} readonly {%endif%} required value = {{kedatangan.sakit}}  >
	          </div>
	        </div>
	        <div class="form-group row">
	          <label class="control-label col-sm-5" for="sakit"> Simpan data diri 	:</label>
	          	<label class="radio-inline col-sm-2">
	            <input type="radio"  name="save" id="save" class="save" value="1"> Ya
	        	</label>
	        	<label class="radio-inline col-sm-2">
	            <input type="radio"  name="save" id="save" class="save" value = "0" > Tidak
	        	</label>
	        </div>
	        <div class="form-group row"  >
  			<input type="hidden" id = "Image" name = "Image">
  				<div class="col-sm-6"> 
		  			<a href={%url 'bukutamu:index'%}><input type="button" name="cancel" id = "cancel" class="col-sm-11 center" value="cancel"></a>
	  			</div>
  				{%if flag%}
  				
	  			<div class="col-sm-6"> 
		  			<input type="submit" name="submit" id = "submit" class="col-sm-11 btn">
	  			</div>
	  			
	  			{%else%}
	  			<div class="col-sm-6"> 
	  				<input id="cancel " type="submit" name="submit" id = "submit" class="col-sm-11 center btn" value = "logout">
	  			</div>
	  			{%endif%}
	  			
  			</div>
  		</form>
    </div>
  </div>
  </div>
</div>

{%if flag%}
<script>
  
  const player = document.getElementById('player');
  const canvas = document.getElementById('canvas');
  const context = canvas.getContext('2d');
  const image = document.getElementById('Image')
  const radio_sakit = document.getElementById('sakit_radio_y')
  const radio_sakitn = document.getElementById('sakit_radio_n')
  const sakit = document.getElementById('Sakit')
  const lukay = document.getElementById('Luka1')
  const lukan = document.getElementById('Luka2')
  var sakit_flag = false
  const nama = document.getElementById("Nama")
  const hp = document.getElementById("NoHP")
  const inst = document.getElementById("Institusi")
  const suhu_badan = document.getElementById("Suhu")
  const bertemu = document.getElementById("Bertemu")
  const keperluan = document.getElementById("Keperluan")
  const submit = document.getElementById("submit")
  const flag = {{flag_auth}}
  const departemen = document.getElementById("departemen")

  if (!flag){
  	suhu_badan.disabled = true
  	bertemu.disabled = true
  	keperluan.disabled = true
  	radio_sakit.disabled = true
  	radio_sakitn.disabled = true
  	submit.disabled = true
  	lukay.disabled = true
  	lukan.disabled = true
  	departemen.disabled = true
  	alert("anda telah melakukan pelanggaran lebih dari 3 kali")
  }

  const constraints = {
    video: true,
  };
  function cameracapture (){
  	// Draw the video frame to the canvas.
    handler = document.getElementById('image_location')
    handler = player
    context.drawImage(player, 0, 0, canvas.width, canvas.height);
     //get image
      var Pic = document.getElementById("canvas").toDataURL();
      Pic = Pic.replace(/^data:image\/(png|jpg);base64,/, "");
      image.value = Pic
  }

  function validateForm(){
  	if (sakit_flag == true){
  		sakit.value = "";
  	}
  	cameracapture();
  }

  function sakit_aktive(){
	sakit_flag = !sakit_flag
	sakit.readOnly = sakit_flag
	sakit.required = !sakit_flag
  }


  // Attach the video stream to the video element and autoplay.
  navigator.mediaDevices.getUserMedia(constraints)
    .then((stream) => {
      player.srcObject = stream;
    });
  sakit_aktive()
</script>
{%endif%}
</body>

bukutamu/templates/bukutamu/index.html
<head>
    {% load static %}
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" id="bootstrap-css">

    <link href="{% static "bukutamu/css/index.css" %}" rel="stylesheet">
    <script src="{% static "jquery.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <!------ Include the above in your HEAD tag ---------->
    <title>Bukutamu</title>
</head>

<body background="{% static "indexbackground.jpg" %}">
    <div class="wrapper ">
      <div id="formContent">
        <!-- Tabs Titles -->
        <br>

        <br>
        <!-- Icon -->
        
        <!-- Login Form -->
        <form method="POST" action="{%url 'bukutamu:form'%}" class="center">
			{% csrf_token %}
          <input type="text" id="UID" class="form-control" name="UID" placeholder="ID" aria-label="Search" required autofocus>
          <br>
          <input style="margin-top: 40px; width: 80%; text-align: center;" type="submit" class="" value="Log In">
         </form>

    
      </div>
    </div>
</body>